import { AuthController } from "./auth.controller";
import { InfoController } from "./info.controller";
import { PersonalController } from "./personal.controller";
import { ClienteController } from "./cliente.controller";
import { InitController } from "./init.controller";
import { SucursalController } from "./sucursal.controller";
import { ObjetivoController } from "./objetivo.controller";
import { AsistenciaController } from "./asistencia.controller";
import { AdelantosController } from "../adelantos/adelantos.controller";
import { TelefoniaController } from "../telefonia/telefonia.controller";
import { ImpuestosAfipController } from "../impuestos-afip/impuestos-afip.controller";
import { CategoriasController } from "../categorias-cambio/categorias-cambio.controller";
import { ObjetivosPendasisController } from "../objetivos-pendasis/objetivos-pendasis.controller";
import { MovimientosAutomaticosController } from "../liquidaciones/movimientos-automaticos/movimientos-automaticos.controller";
import { IngresoPorAsistenciaController } from "../liquidaciones/ingreso-por-asistencia/ingreso-por-asistencia.controller";
import { IngresoPorCustodiaController } from "../liquidaciones/ingreso-por-custodia/ingreso-por-custodia.controller";
import { IngresoAsistenciaAdministrativosArt42Controller } from "../liquidaciones/ingreso-asistencia-administrativos-art42/ingreso-asistencia-administrativos-art42.controller";
import { IngresoCoordinadorCuentaController } from "../liquidaciones/ingreso-coordinador-cuenta/ingreso-coordinador-cuenta.controller";
import { DescuentoPorDeudaAnteriorController } from "../liquidaciones/descuento-deuda-anterior/descuento-deduda-anterior.controller";
import { DescuentosController } from "../liquidaciones/descuentos/descuentos.controller";
import { MovimientoAcreditacionEnCuentaController } from "../liquidaciones/movimiento-acreditacion-cuenta/movimiento-acreditacion-cuenta.controller";
import { LiquidacionesController } from "../liquidaciones/liquidaciones.controller";
import { LiquidacionesBancoController } from "../liquidaciones/liquidaciones-banco/liquidaciones-banco.controller";
import { InformesController } from "../informes/informes.controller";
import { PendienteController } from "../controller/pendiente.controller"
import { DocumentoController } from "../documento/documento.controller"
import { RecibosController } from "../recibos/recibos.controller"
import { PersonalObjetivosController } from "../personal-objetivo/personal-objetivo.controller"
import { CustodiaController } from "./custodia.controller";
import { ListaPermisoCargaController } from "../lista-permisocarga/lista-permisocarga.controller";
import { CargaLicenciaController } from "../carga-licencia/carga-licencia.controller";
import { InasistenciaController } from "../controller/inasistencia.controller";
import { AyudaAsistencialController } from "./ayuda-asistencial.controller"
import { ClientesController } from "../clientes/clientes.controller"
import { FileUploadController } from "./file-upload.controller"
import { ObjetivosController } from "../objetivos/objetivos.controller"
import { AdministradorController } from "../controller/administrador.controller"
import { RubroController } from "../controller/rubro.controller"
import { AccesoBotController } from "../acceso-bot/acceso-bot.controller"
import { SituacionRevistaController } from "../controller/situacionrevista.controller"
import { ResidenciaController } from "../controller/residencia.controller"
import { EstudioController } from "../controller/estudio.controller"
import { PreciosProductosController } from "../precios-productos/precios-productos.controller"
import { DescripcionProductoController } from "./descripcion-producto.controller"
import { GrupoActividadController } from "../grupo-actividad/grupo-actividad.controller"
import { SegurosController } from "../seguros/seguros.controller"
import { ReportesController } from "../reportes/reportes.controller"
import { GestionDescuentosController } from "../gestion-descuentos/gestion-descuentos.controller"
import { CursoController } from "../controller/curso.controller"
import { CentroCapacitacionController } from "../controller/centro-capacitacion.controller"
import { InstitucionesController } from "./instituciones.controller";

export const infoController = new InfoController();
export const authController = new AuthController();
export const personalController = new PersonalController();
export const clienteController = new ClienteController();
export const initController = new InitController();
export const sucursalController = new SucursalController();
export const objetivoController = new ObjetivoController();
export const asistenciaController = new AsistenciaController();
export const adelantosController = new AdelantosController();
export const impuestosAfipController = new ImpuestosAfipController();
export const categoriasController = new CategoriasController();
export const objetivosPendasisController = new ObjetivosPendasisController();
export const telefoniaController = new TelefoniaController();
export const movimientosAutomaticosController = new MovimientosAutomaticosController();
export const ingresoPorAsistenciaController = new IngresoPorAsistenciaController();
export const ingresoPorCustodiaController = new IngresoPorCustodiaController();
export const ingresoAsistenciaAdministrativosArt42Controller = new IngresoAsistenciaAdministrativosArt42Controller();
export const ingresoCoordinadorCuentaController = new IngresoCoordinadorCuentaController();
export const descuentoPorDeudaAnteriorController = new DescuentoPorDeudaAnteriorController();
export const descuentosController = new DescuentosController();
export const movimientoAcreditacionEnCuentaController = new MovimientoAcreditacionEnCuentaController();
export const liquidacionesController = new LiquidacionesController();
export const liquidacionesBancoController = new LiquidacionesBancoController();
export const informesController = new InformesController();
export const pendienteController = new PendienteController();
export const documentoController = new DocumentoController();
export const recibosController = new RecibosController();
export const personalObjetivosController = new PersonalObjetivosController();
export const custodiaController = new CustodiaController();
export const listaPermisoCargaController = new ListaPermisoCargaController();
export const cargaLicenciaController = new CargaLicenciaController();
export const inasistenciaController = new InasistenciaController();
export const ayudaAsistencialController = new AyudaAsistencialController();
export const clientesController = new ClientesController();
export const fileUploadController = new FileUploadController();
export const objetivosController = new ObjetivosController();
export const administradorController = new AdministradorController();
export const rubroController = new RubroController();
export const accesoBotController = new AccesoBotController();
export const situacionRevistaController = new SituacionRevistaController();
export const residenciaController = new ResidenciaController();
export const estudioController = new EstudioController();
export const preciosProductosController = new PreciosProductosController();
export const descripcionProductoController = new DescripcionProductoController();
export const grupoActividadController = new GrupoActividadController();
export const segurosController = new SegurosController();
export const reportesController = new ReportesController();
export const gestionDescuentosController = new GestionDescuentosController();
export const cursoController = new CursoController();
export const centroCapacitacionController = new CentroCapacitacionController();
export const institucionesController = new InstitucionesController();
