import { AuthController } from "./auth.controller.ts";
import { InfoController } from "./info.controller.ts";
import { PersonalController } from "./personal.controller.ts";
import { ClienteController } from "./cliente.controller.ts";
import { InitController } from "./init.controller.ts";
import { SucursalController } from "./sucursal.controller.ts";
import { ObjetivoController } from "./objetivo.controller.ts";
import { AsistenciaController } from "./asistencia.controller.ts";
import { AdelantosController } from "../adelantos/adelantos.controller.ts";
import { TelefoniaController } from "../telefonia/telefonia.controller.ts";
import { ImpuestosAfipController } from "../impuestos-afip/impuestos-afip.controller.ts";
import { CategoriasController } from "../categorias-cambio/categorias-cambio.controller.ts";
import { ObjetivosPendasisController } from "../objetivos-pendasis/objetivos-pendasis.controller.ts";
import { MovimientosAutomaticosController } from "../liquidaciones/movimientos-automaticos/movimientos-automaticos.controller.ts";
import { IngresoPorAsistenciaController } from "../liquidaciones/ingreso-por-asistencia/ingreso-por-asistencia.controller.ts";
import { IngresoPorCustodiaController } from "../liquidaciones/ingreso-por-custodia/ingreso-por-custodia.controller.ts";
import { IngresoAsistenciaAdministrativosArt42Controller } from "../liquidaciones/ingreso-asistencia-administrativos-art42/ingreso-asistencia-administrativos-art42.controller.ts";
import { IngresoCoordinadorCuentaController } from "../liquidaciones/ingreso-coordinador-cuenta/ingreso-coordinador-cuenta.controller.ts";
import { DescuentoPorDeudaAnteriorController } from "../liquidaciones/descuento-deuda-anterior/descuento-deduda-anterior.controller.ts";
import { DescuentosController } from "../liquidaciones/descuentos/descuentos.controller.ts";
import { MovimientoAcreditacionEnCuentaController } from "../liquidaciones/movimiento-acreditacion-cuenta/movimiento-acreditacion-cuenta.controller.ts";
import { LiquidacionesController } from "../liquidaciones/liquidaciones.controller.ts";
import { LiquidacionesBancoController } from "../liquidaciones/liquidaciones-banco/liquidaciones-banco.controller.ts";
import { InformesController } from "../informes/informes.controller.ts";
import { PendienteController } from "../controller/pendiente.controller.ts"
import { DocumentoController } from "../documento/documento.controller.ts"
import { RecibosController } from "../recibos/recibos.controller.ts"
import { PersonalObjetivosController } from "../personal-objetivo/personal-objetivo.controller.ts"
import { CustodiaController } from "./custodia.controller.ts";
import { ListaPermisoCargaController } from "../lista-permisocarga/lista-permisocarga.controller.ts";
import { CargaLicenciaController } from "../carga-licencia/carga-licencia.controller.ts";
import { InasistenciaController } from "../controller/inasistencia.controller.ts";
import { AyudaAsistencialController } from "./ayuda-asistencial.controller.ts"
import { ClientesController } from "../clientes/clientes.controller.ts"
import { FileUploadController } from "./file-upload.controller.ts"
import { ObjetivosController } from "../objetivos/objetivos.controller.ts"
import { AdministradorController } from "../controller/administrador.controller.ts"
import { RubroController } from "../controller/rubro.controller.ts"
import { AccesoBotController } from "../acceso-bot/acceso-bot.controller.ts"
import { SituacionRevistaController } from "../controller/situacionrevista.controller.ts"
import { EstudioController } from "../controller/estudio.controller.ts"
import { PreciosProductosController } from "../precios-productos/precios-productos.controller.ts"
import { DescripcionProductoController } from "./descripcion-producto.controller.ts"
import { GrupoActividadController } from "../grupo-actividad/grupo-actividad.controller.ts"
import { SegurosController } from "../seguros/seguros.controller.ts"
import { ReportesController } from "../reportes/reportes.controller.ts"
import { GestionDescuentosController } from "../gestion-descuentos/gestion-descuentos.controller.ts"
import { CursoController } from "../controller/curso.controller.ts"
import { CentroCapacitacionController } from "../controller/centro-capacitacion.controller.ts"
import { InstitucionesController } from "./instituciones.controller.ts";
import { ActasController } from "../actas/actas.controller.ts";
import { AdministradoresController } from "../administradores/administradores.controller.ts";
import { ImporteVentaVigilanciaController } from "../importe-venta-vigilancia/importe-venta-vigilancia.controller.ts";
import { FacturacionController } from "../facturacion/facturacion.controller.ts";
import { NovedadesController } from "../novedades/novedades.controller.ts";
import { ProcesosAutomaticosController } from "../procesos-automaticos/procesos-automaticos.controller.ts";
import { ExcepcionesAsistenciaController } from "../excepciones-asistencia/excepciones-asistencia.controller.ts";
import { CompensaGeneralACordinadorController } from "../liquidaciones/compensa-general-a-coordinador/compensa-general-a-coordinador.controller.ts";
import { EfectoController } from "../efecto/efecto.controller.ts";
import { DomicilioController } from "../domicilio/domicilio.controller.ts";
import { HabilitacionesController } from "../habilitaciones/habilitaciones.controller.ts";
import { CondicionesVentaController } from "../condiciones-venta/condiciones-venta.controller.ts";
import { SalarioMinimoVitalMovilController } from "../salario-minimo-vital-movil/salario-minimo-vital-movil.controller.ts";

export const infoController = new InfoController();
export const authController = new AuthController();
export const personalController = new PersonalController();
export const clienteController = new ClienteController();
export const initController = new InitController();
export const sucursalController = new SucursalController();
export const objetivoController = new ObjetivoController();
export const asistenciaController = new AsistenciaController();
export const adelantosController = new AdelantosController();
export const impuestosAfipController = new ImpuestosAfipController();
export const categoriasController = new CategoriasController();
export const objetivosPendasisController = new ObjetivosPendasisController();
export const telefoniaController = new TelefoniaController();
export const movimientosAutomaticosController = new MovimientosAutomaticosController();
export const ingresoPorAsistenciaController = new IngresoPorAsistenciaController();
export const ingresoPorCustodiaController = new IngresoPorCustodiaController();
export const ingresoAsistenciaAdministrativosArt42Controller = new IngresoAsistenciaAdministrativosArt42Controller();
export const ingresoCoordinadorCuentaController = new IngresoCoordinadorCuentaController();
export const descuentoPorDeudaAnteriorController = new DescuentoPorDeudaAnteriorController();
export const descuentosController = new DescuentosController();
export const movimientoAcreditacionEnCuentaController = new MovimientoAcreditacionEnCuentaController();
export const liquidacionesController = new LiquidacionesController();
export const liquidacionesBancoController = new LiquidacionesBancoController();
export const informesController = new InformesController();
export const pendienteController = new PendienteController();
export const documentoController = new DocumentoController();
export const recibosController = new RecibosController();
export const personalObjetivosController = new PersonalObjetivosController();
export const custodiaController = new CustodiaController();
export const listaPermisoCargaController = new ListaPermisoCargaController();
export const cargaLicenciaController = new CargaLicenciaController();
export const inasistenciaController = new InasistenciaController();
export const ayudaAsistencialController = new AyudaAsistencialController();
export const clientesController = new ClientesController();
export const fileUploadController = new FileUploadController();
export const objetivosController = new ObjetivosController();
export const administradorController = new AdministradorController();
export const rubroController = new RubroController();
export const accesoBotController = new AccesoBotController();
export const situacionRevistaController = new SituacionRevistaController();
export const domicilioController = new DomicilioController();
export const estudioController = new EstudioController();
export const preciosProductosController = new PreciosProductosController();
export const descripcionProductoController = new DescripcionProductoController();
export const grupoActividadController = new GrupoActividadController();
export const segurosController = new SegurosController();
export const reportesController = new ReportesController();
export const gestionDescuentosController = new GestionDescuentosController();
export const cursoController = new CursoController();
export const centroCapacitacionController = new CentroCapacitacionController();
export const institucionesController = new InstitucionesController();
export const actasController = new ActasController()
export const administradoresController = new AdministradoresController()
export const importeVentaVigilanciaController = new ImporteVentaVigilanciaController()
export const facturacionController = new FacturacionController()
export const novedadesController = new NovedadesController()
export const procesosAutomaticosController = new ProcesosAutomaticosController()
export const excepcionesAsistenciaController = new ExcepcionesAsistenciaController()
export const compensaGeneralACordinadorController = new CompensaGeneralACordinadorController()
export const efectoController = new EfectoController()
export const habilitacionesController = new HabilitacionesController()
export const condicionesVentaController = new CondicionesVentaController()
export const salarioMinimoVitalMovilController = new SalarioMinimoVitalMovilController()